
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: first_job
    steps:
    - bash: rtrt
  - job: check_ant_version
    steps:
    - bash: exit 1
      continueOnError: true
 
  dependsOn: build
  jobs:
  - job: second_job
    steps:
    - bash: echo this is second job from second stage

- stage: prod
  dependsOn: build
  jobs:
  - job: third_job
    steps:
    - bash: echo this is third job from third stage

- stage: prod1
  dependsOn:
   - build
   - dev
   - prod
  jobs:
  - job: forth_job
    steps:
    - bash: echo this is forth job from forth stage