
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: first_job
    steps:
    - bash: echo this is first job from first stage

- stage: dev
  jobs:
  - job: second_job
    steps:
    - bash: echo this is second job from second stage