
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: first_job
    steps:
    - bash: echo this is first job from first stage
  - job: check_ant_version
    steps:
    - bash: ant --version    

- stage: dev
  dependsOn: build
  jobs:
  - job: second_job
    steps:
    - bash: echo this is second job from second stage

- stage: prod
  dependsOn: build
  jobs:
  - job: third_job
    steps:
    - bash: echo this is third job from third stage